SMODS.Challenge {
    key = 'ins_mycologist_1',
    rules = {
        custom = {
            { id = 'no_shop_jokers' },
			{ id = 'no_reward_specific', value = 'Small' },
            { id = 'no_reward_specific', value = 'Big' },
        }
    },
    jokers = {
        { id = 'j_felijo_ins_myco', eternal = true},
		{ id = 'j_jolly', eternal = true},
    },
	consumeables = {
		{ id = 'c_mercury'},
	},
	vouchers = {
		{ id = 'v_magic_trick'},
		{ id = 'v_overstock_norm'},
    },
    restrictions = {
		banned_cards = {
			{ id = 'c_judgement' },
			{ id = 'c_wraith' },
			{ id = 'c_soul' },
			{ id = 'v_antimatter' },
			{ id = 'p_buffoon_normal_1', ids = {'p_buffoon_normal_1', 'p_buffoon_normal_2', 'p_buffoon_jumbo_1', 'p_buffoon_mega_1'}},
			
		},
		banned_tags = {
			{ id = 'tag_uncommon' },
			{ id = 'tag_rare' },
			{ id = 'tag_negative' },
			{ id = 'tag_foil' },
			{ id = 'tag_holographic' },
			{ id = 'tag_polychrome' },
			{ id = 'tag_buffoon' },
			{ id = 'tag_top_up' },
		},
		banned_other = {
			{ id = 'felijo_sgl_trifurcated', type = 'sticker' },
			{ id = 'bl_final_heart', type = 'blind' },
            { id = 'bl_final_leaf',  type = 'blind' },
            { id = 'bl_final_acorn', type = 'blind' },
		},
    },

    deck = {
        type = 'Challenge Deck',
        cards = {
            { s = 'C', r = 'A' },
            { s = 'D', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'S', r = 'A' },
            { s = 'C', r = 'K'},
            { s = 'D', r = 'K'},
            { s = 'H', r = 'K'},
            { s = 'S', r = 'K'},
            { s = 'C', r = 'Q'},
            { s = 'D', r = 'Q'},
            { s = 'H', r = 'Q'},
            { s = 'S', r = 'Q'},
            { s = 'C', r = 'J'},
            { s = 'D', r = 'J'},
            { s = 'H', r = 'J'},
            { s = 'S', r = 'J'},
            { s = 'C', r = 'T' },
            { s = 'D', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'S', r = 'T' },
            { s = 'C', r = '9' },
            { s = 'D', r = '9' },
            { s = 'H', r = '9' },
            { s = 'S', r = '9' },
            { s = 'C', r = '8' },
            { s = 'D', r = '8' },
            { s = 'H', r = '8' },
            { s = 'S', r = '8' },
            { s = 'C', r = '7' },
            { s = 'D', r = '7' },
            { s = 'H', r = '7' },
            { s = 'S', r = '7' },
            { s = 'C', r = '6' },
            { s = 'D', r = '6' },
            { s = 'H', r = '6' },
            { s = 'S', r = '6' },
            { s = 'C', r = '5' },
            { s = 'D', r = '5' },
            { s = 'H', r = '5' },
            { s = 'S', r = '5' },
            { s = 'C', r = '4' },
            { s = 'D', r = '4' },
            { s = 'H', r = '4' },
            { s = 'S', r = '4' },
            { s = 'C', r = '3' },
            { s = 'D', r = '3' },
            { s = 'H', r = '3' },
            { s = 'S', r = '3' },
            { s = 'C', r = '2' },
            { s = 'D', r = '2' },
            { s = 'H', r = '2' },
            { s = 'S', r = '2' },
        }
    }
}


SMODS.Challenge {
    key = 'stock_1',
    rules = {
        custom = {
			{ id = 'no_reward_specific', value = 'Small' },
            { id = 'no_reward_specific', value = 'Big' },
        },
		modifiers = {
            { id = 'dollars', value = 25 },
        }
    },
    jokers = {
        { id = 'j_felijo_stock_exchange', eternal = true},
		{ id = 'j_bull', eternal = true},
		{ id = 'j_bootstraps', eternal = true},
    },
	consumeables = {
	},
	vouchers = {
		{ id = 'v_clearance_sale' },
        { id = 'v_liquidation' },
    },
    restrictions = {
		banned_cards = {
			{ id = 'c_hermit' },
			{ id = 'c_temperance' },
			{ id = 'c_immolate'},
			{ id = 'v_seed_money' },
			{ id = 'v_money_tree' },
			{ id = 'v_felijo_beartrap' },
			{ id = 'v_felijo_peltmarket' },
			{ id = 'j_to_the_moon' },
            { id = 'j_rocket' },
            { id = 'j_mail' },
			{ id = 'j_reserved_parking' },
			{ id = 'j_business'},
			{ id = 'j_matador'},
			{ id = 'j_todo_list'},
			{ id = 'j_delayed_grat'},
            { id = 'j_golden' },
            { id = 'j_satellite' },
			{ id = 'j_egg' },
			{ id = 'j_credit_card' },
			{ id = 'j_golden' },
			{ id = 'j_gift' },
			{ id = 'j_ticket' },
			
			
		},
		banned_tags = {
			{ id = 'tag_garbage' },
			{ id = 'tag_economy' },
			{ id = 'tag_handy' },
			{ id = 'tag_investment' },
		},
		banned_other = {
			{ id = 'felijo_sgl_trifurcated', type = 'sticker' },
			{ id = 'felijo_sgl_bifurcated', type = 'sticker' },
			{ id = 'bl_tooth', type = 'blind' },
		},
    },

    deck = {
        type = 'Challenge Deck',
        cards = {
            { s = 'C', r = 'A' },
            { s = 'D', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'S', r = 'A' },
            { s = 'C', r = 'K'},
            { s = 'D', r = 'K'},
            { s = 'H', r = 'K'},
            { s = 'S', r = 'K'},
            { s = 'C', r = 'Q'},
            { s = 'D', r = 'Q'},
            { s = 'H', r = 'Q'},
            { s = 'S', r = 'Q'},
            { s = 'C', r = 'J'},
            { s = 'D', r = 'J'},
            { s = 'H', r = 'J'},
            { s = 'S', r = 'J'},
            { s = 'C', r = 'T' },
            { s = 'D', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'S', r = 'T' },
            { s = 'C', r = '9' },
            { s = 'D', r = '9' },
            { s = 'H', r = '9' },
            { s = 'S', r = '9' },
            { s = 'C', r = '8' },
            { s = 'D', r = '8' },
            { s = 'H', r = '8' },
            { s = 'S', r = '8' },
            { s = 'C', r = '7' },
            { s = 'D', r = '7' },
            { s = 'H', r = '7' },
            { s = 'S', r = '7' },
            { s = 'C', r = '6' },
            { s = 'D', r = '6' },
            { s = 'H', r = '6' },
            { s = 'S', r = '6' },
            { s = 'C', r = '5' },
            { s = 'D', r = '5' },
            { s = 'H', r = '5' },
            { s = 'S', r = '5' },
            { s = 'C', r = '4' },
            { s = 'D', r = '4' },
            { s = 'H', r = '4' },
            { s = 'S', r = '4' },
            { s = 'C', r = '3' },
            { s = 'D', r = '3' },
            { s = 'H', r = '3' },
            { s = 'S', r = '3' },
            { s = 'C', r = '2' },
            { s = 'D', r = '2' },
            { s = 'H', r = '2' },
            { s = 'S', r = '2' },
        }
    }
}
SMODS.Challenge {
    key = 'stock_2',
    rules = {
        custom = {
			{ id = 'no_reward_specific', value = 'Small' },
            { id = 'no_reward_specific', value = 'Big' },
        },
		modifiers = {
            { id = 'dollars', value = 25 },
        }
    },
    jokers = {
        { id = 'j_felijo_stock_exchange', eternal = true},
		{ id = 'j_bull', eternal = true},
		{ id = 'j_bootstraps', eternal = true},
		{ id = 'j_oops', eternal = true},
		{ id = 'j_oops', eternal = true},
    },
	consumeables = {
	},
	vouchers = {
		{ id = 'v_clearance_sale' },
        { id = 'v_liquidation' },
    },
    restrictions = {
		banned_cards = {
			{ id = 'c_hermit' },
			{ id = 'c_temperance' },
			{ id = 'c_immolate'},
			{ id = 'v_seed_money' },
			{ id = 'v_money_tree' },
			{ id = 'v_felijo_beartrap' },
			{ id = 'v_felijo_peltmarket' },
			{ id = 'j_to_the_moon' },
            { id = 'j_rocket' },
            { id = 'j_mail' },
			{ id = 'j_reserved_parking' },
			{ id = 'j_business'},
			{ id = 'j_matador'},
			{ id = 'j_todo_list'},
			{ id = 'j_delayed_grat'},
            { id = 'j_golden' },
            { id = 'j_satellite' },
			{ id = 'j_egg' },
			{ id = 'j_credit_card' },
			{ id = 'j_golden' },
			{ id = 'j_gift' },
			{ id = 'j_ticket' },
			
			
		},
		banned_tags = {
			{ id = 'tag_garbage' },
			{ id = 'tag_economy' },
			{ id = 'tag_handy' },
			{ id = 'tag_investment' },
		},
		banned_other = {
			{ id = 'felijo_sgl_trifurcated', type = 'sticker' },
			{ id = 'felijo_sgl_bifurcated', type = 'sticker' },
			{ id = 'bl_tooth', type = 'blind' },
		},
    },

    deck = {
        type = 'Challenge Deck',
        cards = {
            { s = 'C', r = 'A' },
            { s = 'D', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'S', r = 'A' },
            { s = 'C', r = 'K'},
            { s = 'D', r = 'K'},
            { s = 'H', r = 'K'},
            { s = 'S', r = 'K'},
            { s = 'C', r = 'Q'},
            { s = 'D', r = 'Q'},
            { s = 'H', r = 'Q'},
            { s = 'S', r = 'Q'},
            { s = 'C', r = 'J'},
            { s = 'D', r = 'J'},
            { s = 'H', r = 'J'},
            { s = 'S', r = 'J'},
            { s = 'C', r = 'T' },
            { s = 'D', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'S', r = 'T' },
            { s = 'C', r = '9' },
            { s = 'D', r = '9' },
            { s = 'H', r = '9' },
            { s = 'S', r = '9' },
            { s = 'C', r = '8' },
            { s = 'D', r = '8' },
            { s = 'H', r = '8' },
            { s = 'S', r = '8' },
            { s = 'C', r = '7' },
            { s = 'D', r = '7' },
            { s = 'H', r = '7' },
            { s = 'S', r = '7' },
            { s = 'C', r = '6' },
            { s = 'D', r = '6' },
            { s = 'H', r = '6' },
            { s = 'S', r = '6' },
            { s = 'C', r = '5' },
            { s = 'D', r = '5' },
            { s = 'H', r = '5' },
            { s = 'S', r = '5' },
            { s = 'C', r = '4' },
            { s = 'D', r = '4' },
            { s = 'H', r = '4' },
            { s = 'S', r = '4' },
            { s = 'C', r = '3' },
            { s = 'D', r = '3' },
            { s = 'H', r = '3' },
            { s = 'S', r = '3' },
            { s = 'C', r = '2' },
            { s = 'D', r = '2' },
            { s = 'H', r = '2' },
            { s = 'S', r = '2' },
        }
    }
}