SMODS.Challenge {
    key = 'ins_mycologist_1',
    rules = {
        custom = {
            { id = 'no_shop_jokers' },
			{ id = 'no_reward_specific', value = 'Small' },
            { id = 'no_reward_specific', value = 'Big' },
        }
    },
    jokers = {
        { id = 'j_felijo_ins_myco', eternal = true},
		{ id = 'j_jolly', eternal = true},
    },
	consumeables = {
		{ id = 'c_mercury'},
	},
	vouchers = {
		{ id = 'v_magic_trick'},
		{ id = 'v_overstock_norm'},
    },
    restrictions = {
		banned_cards = {
			{ id = 'c_judgement' },
			{ id = 'c_wraith' },
			{ id = 'c_soul' },
			{ id = 'v_antimatter' },
			{ id = 'p_buffoon_normal_1', ids = {'p_buffoon_normal_1', 'p_buffoon_normal_2', 'p_buffoon_jumbo_1', 'p_buffoon_mega_1'}},
			
		},
		banned_tags = {
			{ id = 'tag_uncommon' },
			{ id = 'tag_rare' },
			{ id = 'tag_negative' },
			{ id = 'tag_foil' },
			{ id = 'tag_holographic' },
			{ id = 'tag_polychrome' },
			{ id = 'tag_buffoon' },
			{ id = 'tag_top_up' },
		},
		banned_other = {
			{ id = 'felijo_sgl_trifurcated', type = 'sticker' },
			{ id = 'bl_final_heart', type = 'blind' },
            { id = 'bl_final_leaf',  type = 'blind' },
            { id = 'bl_final_acorn', type = 'blind' },
		},
    },

    deck = {
        type = 'Challenge Deck',
        cards = {
            { s = 'C', r = 'A' },
            { s = 'D', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'S', r = 'A' },
            { s = 'C', r = 'K'},
            { s = 'D', r = 'K'},
            { s = 'H', r = 'K'},
            { s = 'S', r = 'K'},
            { s = 'C', r = 'Q'},
            { s = 'D', r = 'Q'},
            { s = 'H', r = 'Q'},
            { s = 'S', r = 'Q'},
            { s = 'C', r = 'J'},
            { s = 'D', r = 'J'},
            { s = 'H', r = 'J'},
            { s = 'S', r = 'J'},
            { s = 'C', r = 'T' },
            { s = 'D', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'S', r = 'T' },
            { s = 'C', r = '9' },
            { s = 'D', r = '9' },
            { s = 'H', r = '9' },
            { s = 'S', r = '9' },
            { s = 'C', r = '8' },
            { s = 'D', r = '8' },
            { s = 'H', r = '8' },
            { s = 'S', r = '8' },
            { s = 'C', r = '7' },
            { s = 'D', r = '7' },
            { s = 'H', r = '7' },
            { s = 'S', r = '7' },
            { s = 'C', r = '6' },
            { s = 'D', r = '6' },
            { s = 'H', r = '6' },
            { s = 'S', r = '6' },
            { s = 'C', r = '5' },
            { s = 'D', r = '5' },
            { s = 'H', r = '5' },
            { s = 'S', r = '5' },
            { s = 'C', r = '4' },
            { s = 'D', r = '4' },
            { s = 'H', r = '4' },
            { s = 'S', r = '4' },
            { s = 'C', r = '3' },
            { s = 'D', r = '3' },
            { s = 'H', r = '3' },
            { s = 'S', r = '3' },
            { s = 'C', r = '2' },
            { s = 'D', r = '2' },
            { s = 'H', r = '2' },
            { s = 'S', r = '2' },
        }
    }
}